[package]
name = "gpu_evolve_texture"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_reflect = "0.8.1"
bevy_render = "0.8.1"
bevy_asset = "0.8.1"
bevy_sprite = "0.8.1"
bevy_app = "0.8.1"
bevy_ecs = "0.8.1"

[dev-dependencies]
bevy = "0.8.1"
anyhow = "1.0.65"
